parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\GoogleAnalyticsMeasurementProtocol\FirebaseMeasurementProtocolService:
        arguments:
            - api_secret
            - firebase_app_id

    App\Service\GoogleAnalyticsMeasurementProtocol\GtagMeasurementProtocolService:
        arguments:
            - api_secret
            - measurement_id
