parameters:
    google_analytics_measurement_protocol:
        api_secret: null
        measurement_id: null
        firebase_app_id: null
        measurement_protocol_host: 'https://www.google-analytics.com'
        measurement_protocol_path: '/mp/collect'
        debug: false
        debug_path: '/debug'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\GoogleAnalyticsMeasurementProtocol\FirebaseMeasurementProtocolService:
        arguments:
            - api_secret
            - firebase_app_id

    App\Service\GoogleAnalyticsMeasurementProtocol\GtagMeasurementProtocolService:
        arguments:
            - api_secret
            - measurement_id
